
// libnx/hid.h
typedef enum HidNpadButton : unsigned long long {
	HidNpadButton_A = (1ULL << (0)),
	HidNpadButton_B = (1ULL << (1)),
	HidNpadButton_X = (1ULL << (2)),
	HidNpadButton_Y = (1ULL << (3)),
	HidNpadButton_StickL = (1ULL << (4)),
	HidNpadButton_StickR = (1ULL << (5)),
	HidNpadButton_L = (1ULL << (6)),
	HidNpadButton_R = (1ULL << (7)),
	HidNpadButton_ZL = (1ULL << (8)),
	HidNpadButton_ZR = (1ULL << (9)),
	HidNpadButton_Plus = (1ULL << (10)),
	HidNpadButton_Minus = (1ULL << (11)),
	HidNpadButton_Left = (1ULL << (12)),
	HidNpadButton_Up = (1ULL << (13)),
	HidNpadButton_Right = (1ULL << (14)),
	HidNpadButton_Down = (1ULL << (15)),
	HidNpadButton_StickLLeft = (1ULL << (16)),
	HidNpadButton_StickLUp = (1ULL << (17)),
	HidNpadButton_StickLRight = (1ULL << (18)),
	HidNpadButton_StickLDown = (1ULL << (19)),
	HidNpadButton_StickRLeft = (1ULL << (20)),
	HidNpadButton_StickRUp = (1ULL << (21)),
	HidNpadButton_StickRRight = (1ULL << (22)),
	HidNpadButton_StickRDown = (1ULL << (23)),
	HidNpadButton_LeftSL = (1ULL << (24)),
	HidNpadButton_LeftSR = (1ULL << (25)),
	HidNpadButton_RightSL = (1ULL << (26)),
	HidNpadButton_RightSR = (1ULL << (27)),
	HidNpadButton_Palma = (1ULL << (28)),
	HidNpadButton_Verification = (1ULL << (29)),
	HidNpadButton_HandheldLeftB = (1ULL << (30)),
	HidNpadButton_LagonCLeft = (1ULL << (31)),
	HidNpadButton_LagonCUp = (1ULL << (32)),
	HidNpadButton_LagonCRight = (1ULL << (33)),
	HidNpadButton_LagonCDown = (1ULL << (34)),
	HidNpadButton_AnyLeft = HidNpadButton_Left | HidNpadButton_StickLLeft | HidNpadButton_StickRLeft,
	HidNpadButton_AnyUp = HidNpadButton_Up | HidNpadButton_StickLUp | HidNpadButton_StickRUp,
	HidNpadButton_AnyRight = HidNpadButton_Right | HidNpadButton_StickLRight | HidNpadButton_StickRRight,
	HidNpadButton_AnyDown = HidNpadButton_Down | HidNpadButton_StickLDown | HidNpadButton_StickRDown,
	HidNpadButton_AnySL = HidNpadButton_LeftSL | HidNpadButton_RightSL,
	HidNpadButton_AnySR = HidNpadButton_LeftSR | HidNpadButton_RightSR
};